version: '3.8'

services:
  redis:
    image: redis:7.2-alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    environment:
      REDIS_PASSWORD: "" 
      REDIS_TTL: "5"    
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      - weatherbot-net

  weatherbot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: weatherbot
    restart: unless-stopped
    depends_on:
      redis:
        condition: service_healthy
    ports:
      - "8080:8080"
    volumes:
      - ./config:/etc/weatherbot/config
      - ./logs:/var/log/weatherbot      
    environment:
      - TZ=Europe/Moscow             
      - REDIS_ADDR=redis:6379          
    networks:
      - weatherbot-net

volumes:
  redis_data:
    driver: local

networks:
  weatherbot-net:
    driver: bridge